// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCe688FBSVkPb6qmmyKctlBFKDODupAILg',
    appId: '1:278280175866:web:ed58ed2847882c1f7a0943',
    messagingSenderId: '278280175866',
    projectId: 'learning-firebase-e5fe7',
    authDomain: 'learning-firebase-e5fe7.firebaseapp.com',
    storageBucket: 'learning-firebase-e5fe7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkDaEl0-XjYrK70lATB73Eh9BP870BnlE',
    appId: '1:278280175866:android:033b3eed15bf28627a0943',
    messagingSenderId: '278280175866',
    projectId: 'learning-firebase-e5fe7',
    storageBucket: 'learning-firebase-e5fe7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNQjOeoti-c4Qxo0s3ZMlRqZywwgy90eo',
    appId: '1:278280175866:ios:04d66710cdc2afa17a0943',
    messagingSenderId: '278280175866',
    projectId: 'learning-firebase-e5fe7',
    storageBucket: 'learning-firebase-e5fe7.appspot.com',
    iosClientId: '278280175866-19fn08kc03hph83cfd24cacrmg97hqmm.apps.googleusercontent.com',
    iosBundleId: 'com.example.freelancerFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNQjOeoti-c4Qxo0s3ZMlRqZywwgy90eo',
    appId: '1:278280175866:ios:04d66710cdc2afa17a0943',
    messagingSenderId: '278280175866',
    projectId: 'learning-firebase-e5fe7',
    storageBucket: 'learning-firebase-e5fe7.appspot.com',
    iosClientId: '278280175866-19fn08kc03hph83cfd24cacrmg97hqmm.apps.googleusercontent.com',
    iosBundleId: 'com.example.freelancerFirebase',
  );
}
